/** Browser-safe inputs and complete files for one reproducible research report. */
import type { Branded } from '@deepseek-ai/dsh-brand';
import type { ResearchQuestionId } from '../research-information/types.ts';
/** SHA-256 of the ordered file names, media types, and exact text contents. */
export type ResearchReportDigest = Branded<'ResearchReportDigest'>;
/** Export the inspected question revision; concurrent changes require a fresh preview. */
export interface ResearchReportRequest {
    readonly questionId: ResearchQuestionId;
    readonly expectedRevision: number;
}
/** One UTF-8 file; names are generated by the renderer and contain no user-provided paths. */
export interface ResearchReportFile {
    readonly name: 'report.md' | 'report.tex' | 'references.bib' | 'references.csl.json' | 'provenance.json';
    readonly mediaType: string;
    readonly text: string;
}
/** Complete report and audit files from the same question and bibliographic snapshot. */
export interface ResearchReportBundle {
    readonly questionId: ResearchQuestionId;
    readonly revision: number;
    readonly digest: ResearchReportDigest;
    readonly files: readonly ResearchReportFile[];
    readonly summary: {
        readonly currentClaims: number;
        readonly unreviewedClaims: number;
        readonly rejectedClaims: number;
        readonly includedFindings: number;
        readonly excludedFindings: number;
        readonly evidenceCount: number;
        readonly missingFacetCount: number;
    };
}
/** Export refusal never mutates the question or publishes partial files. */
export type ResearchReportResult = {
    readonly status: 'ready';
    readonly bundle: ResearchReportBundle;
} | {
    readonly status: 'question-not-found';
} | {
    readonly status: 'stale-revision';
    readonly currentRevision: number;
} | {
    readonly status: 'capacity';
    readonly maxReportBytes: number;
};
//# sourceMappingURL=types.d.ts.map